hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl:
    auto: create
  show_sql: true
  
server:
  port: 8080
  
spring:
  application:
    name: library-management-system
  profile:
    active: test
  cloud:
    config:
      profile: test
  config:
    activate:
      on-profile: test
    import: optional:configserver:http://localhost:9898
  security:
    enabled: true
    user:
      name: Hitho
      password: password
  jpa:
    driverClassName: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource: 
    url: jdbc:mysql://localhost:3306/lmsdb?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: ''
    driver: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: saazhsh@gmail.com
    password: uduv xgty zwwj ckad
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-location: classpath:/static/
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

